site_name: osgEarth
repo_name: 'gwaldron/osgearth'
repo_url: 'https://github.com/gwaldron/osgearth'
site_url: 'http://osgearth.org'
     
theme:
  name: readthedocs
  include_sidebar: true
    
plugins:
  - search

pages:
  - Introduction: "index.md"
  - Installing: "install.md"
  - Building: "build.md"
  - Preparing Data: "data.md"
  - 3.x Upgrade Guide: "3.0_upgrade_guide.md"
  - FAQ: "faq.md"
  - Release Notes: "releasenotes.md"
