site_name: osgEarth
site_url: http://osgearth.org
site_decription: osgEarth SDK
site_author: Pelican Mapping

repo_url: https://github.com/gwaldron/osgearth/
edit_uri: ""
     
theme:
    name: readthedocs
    include_sidebar: true
    
plugins:
    - search
    
markdown_extension:
    - toc:
        permalink: 
    - admonition
    - def_list

pages:
    - Home: index.md
    - Installing: install.md
    - Building: build.md
    - Preparing Data: data.md
    - 3.x Upgrade Guide: 3.0_upgrade_guide.md
    - FAQ: faq.md
    - Release Notes: releasenotes.md
